org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
neo_version_range=[21.1,)
loader_version_range=[1,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=chunky_friends
mod_name=Chunky Friends
mod_license=MIT
mod_version=1.1.2+mc1.21.1-neoforge
mod_group_id=com.onthehill.chunkyfriends

chunky_version=1.4.23
junit_version=5.14.2
